### ISSUE TITLE
Share your config

### ISSUE THREAD

**Issue by cutbypham** [jbensmann/mouseless#25]

**Comment by benjaminbhollon** [comment]
Here's mine: https://codeberg.org/benjaminhollon/.dotfiles/src/branch/main/.config/mouseless/config.yaml

Pretty complex, I know, but I'm using it to recreate a QMK config I have. :)

**Comment by thuanowa** [comment]
update my config switching to pop shell

```yaml
# the keyboard devices it reads from, if no devices are specified, it reads from all
devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"

# startCommand: "setxkbmap de"

baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 200.0
mouseAccelerationCurve: 2.0

startMouseSpeed: 0.0

mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
  - name: initial
    bindings:
      a: tap-hold a ; toggle-layer mouse ; 200
      space: tap-hold space ; toggle-layer thuan_fly_keys ; 200
      s: tap-hold s ; toggle-layer popshell ; 200

      # capslock kinda useless for me, so i map it to esc for vim
      capslock: esc

      # key `|\` at the bottom on msi laptop keyboard, why? they put the key in this position
      102nd: leftctrl

      #####################
      # External keyboard #
      #####################

      # key menu
      compose: leftctrl
      f1: mute
      f2: volumedown
      f3: volumeup
      # mic mute, `KEY_MICMUTE` ~ micmute doesn't work, debug show key press is `f20`
      f5: f20
      f8: leftctrl+leftshift+v

  - name: mouse
    passThrough: false
    bindings:
      a: layer initial
      i: layer mouse
      r: reload-config
      l: move  1  0
      h: move -1  0
      j: move  0  1
      k: move  0 -1
      p: scroll up
      semicolon: scroll down
      leftalt: speed 4.0
      space: speed 0.3
      f: button left
      d: button middle
      s: button right

  - name: thuan_fly_keys
    passThrough: true
    bindings:
      # function key kinda far, lazy to reach out
      k1: f1
      k2: f2
      k3: f3
      k4: f4
      k5: f5
      k6: f6
      k7: f7
      k8: f8
      k9: f9
      k0: f10
      minus: f11
      equal: f12

      # pop shell
      a: leftmeta+k1
      s: leftmeta+k2
      d: leftmeta+k3
      f: leftmeta+k4
      g: leftmeta+k5
      q: leftmeta+k6
      w: leftmeta+k7
      e: leftmeta+k8
      r: leftmeta+k9
      t: leftmeta+k0

      # editing text

      k: up
      h: left
      j: down
      l: right
      i: home
      o: end

      # Gnome

      # resize windows
      c: rightalt+f8

      # pano clipboard extension
      v: leftmeta+leftshift+v

      # switch windows to monitor left
      comma: leftmeta+leftshift+left

      # switch windows to monitor right
      dot: leftmeta+leftshift+right

      # popshell toggle maximize
      m: leftmeta+m

      # close window
      x: leftalt+f4

      # browser

      # next tab aka `ctrl + tab`
      p: leftctrl+pagedown

      # previous tab aka `ctrl + shift + tab`
      u: leftctrl+pageup

      # go back
      leftbrace: leftalt+left

      # go forward
      rightbrace: leftalt+right

  - name: popshell
    passThrough: false
    bindings:
      enter: leftmeta+enter
      h: leftmeta+h
      j: leftmeta+j
      k: leftmeta+k
      l: leftmeta+l
      u: leftmeta+leftshift+pageup
      p: leftmeta+leftshift+pagedown
      o: leftmeta+o
      i: leftmeta+s
      semicolon: leftmeta+g
```

**Comment by remembertoremind** [comment]
I'm a simple person who likes simple things. Like, I like when I can control the mouse with one hand, so this is my wsad-suggestion. the right/left mouse button on shift and tab makes sense when I have to drag and drop stuff. I rarely have to, but I'd rather be able to than not. Besides, I rarely use shift and tab when moving the mouse. I have been using this config for about 5  hours and it feels rather natural. Even the easy integration with my browser is a pretty amazing. `mouseless` is easy to set up and easy to use <3

```yaml
# the default speed for mouse movement and scrolling
baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

# the time it takes to accelerate to baseMouseSpeed (in ms), 0 to reach top speed immediately
mouseAccelerationTime: 200.0

# the shape of the acceleration curve, 1.0 is linear, higher values have more time at low speeds
mouseAccelerationCurve: 2.0

# speed of the mouse when it starts moving
startMouseSpeed: 0.0

# same for deceleration
mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
- name: initial
  bindings:
    leftalt: toggle-layer mouse

- name: mouse
  passThrough: false
  bindings:
    g: reload-config
    leftshift: button left
    capslock: button middle
    tab: button right
    d: move  1  0
    a: move -1  0
    s: move  0  1
    w: move  0 -1
    r: scroll up
    f: scroll down

# Qutebrowser   
    q: leftshift+h
    e: leftshift+l
    2: leftshift+k
    3: d
    4: u
    5: leftshift+j
```
