### ISSUE TITLE
Using numbers needs to be +1

### ISSUE THREAD

**Issue by remembertoremind** [jbensmann/mouseless#28]
I use the the config below and wanted to use 1-4 for navigating tabs in my browser. However, I wanted 1 to be back, but `mouseless` needs to be configured with 2 before the command is bound to 1. Therefore, the command bound to 5 is on 4 and 3 on 2. So, all the keys are +1.

```yaml
# the default speed for mouse movement and scrolling
baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

# the time it takes to accelerate to baseMouseSpeed (in ms), 0 to reach top speed immediately
mouseAccelerationTime: 200.0

# the shape of the acceleration curve, 1.0 is linear, higher values have more time at low speeds
mouseAccelerationCurve: 2.0

# speed of the mouse when it starts moving
startMouseSpeed: 0.0

# same for deceleration
mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
- name: initial
  bindings:
    leftalt: toggle-layer mouse

- name: mouse
  passThrough: false
  bindings:
    g: reload-config
    leftshift: button left
    capslock: button middle
    tab: button right
    d: move  1  0
    a: move -1  0
    s: move  0  1
    w: move  0 -1
    r: scroll up
    f: scroll down

# Qutebrowser   
    q: leftshift+h
    e: leftshift+l
    2: leftshift+k
    3: d
    4: u
    5: leftshift+j
```

**Comment by remembertoremind** [comment]
Using k1-k4 is what I should have used. 

 ```yaml
   k1: leftshift+k
    k2: d
    k3: u
    k4: leftshift+j

```
