### ISSUE TITLE
How can we use mouseless with kmonad?

### ISSUE THREAD

**Issue by isaif** [jbensmann/mouseless#4]
I am already using [kmonad](https://github.com/kmonad/kmonad), but I want to know if i can use both kmonad and mouseless together. 

Using debug mode I can see error "Failed to open /dev/input/by-id/usb-CHESEN_USB_Keyboard-event-kbd: device or resource busy". I guess it is because kmonad is already using it. Any fix for this?

**Comment by jbensmann** [comment]
Yeah that is actually possible, only one program can read the original device and the other has to read from the virtual device created by the first program, which is one of/dev/input/event*. For mouseless I think it is always the same, I can check it again when I am back from holidays. Note that the second program has to consider the remappings of the first program.

**Comment by jbensmann** [comment]
Ok it is not always the same, but one can see the device of mouseless or kmonad with `libinput list-devices`, maybe it is at least stable on the same PC. Another option would be to write a script that starts mouseless, finds out the device, replaces the device in the kmonad config and starts kmonad (or the other way around if you want to start kmonad first).

**Comment by isaif** [comment]
I am using linux and would like to start kmonad first. Any help regarding how to write the script will be most helpful.

**Comment by jbensmann** [comment]
Here is an example, it assumes that kmonad is running and that you have specified a device like `/dev/input/event123` in the mouseless config, which is then replaced with the kmonad device. Note that you have to use sudo in case you did not add permissions.
```
#!/usr/bin/env sh
device=$(libinput list-devices | grep -i "kmonad" -A10 | grep "Kernel:" | sed 's_.*\(/dev/input/event[0-9]*\).*_\1_')
[ -z "$device" ] && echo "kmonad device not found" && exit 1
echo "kmonad device found: $device"
sed -i 's_- "/dev/input/event[0-9]*"_- "'"$device"'"_' ~/.config/mouseless/config.yaml
mouseless --config ~/.config/mouseless/config.yaml
```

**Comment by isaif** [comment]
The scirpt is not working and I am getting the same error.

Here is the log I got using `--debug` with the script you provided:
```
kmonad device found: /dev/input/event13
DEBU[0000] Available keyboard devices:                  
DEBU[0000] /dev/input/by-path/pci-0000:00:14.0-usb-0:3:1.0-event-kbd CHESEN USB Keyboard usb-0000:00:14.0-3/input0 
DEBU[0000] /dev/input/by-id/usb-CHESEN_USB_Keyboard-event-kbd CHESEN USB Keyboard usb-0000:00:14.0-3/input0 
DEBU[0000] Using config file: /home/saif/.config/mouseless/config.yaml 
DEBU[0000] config: {Devices:[/dev/input/by-id/usb-CHESEN_USB_Keyboard-event-kbd] StartCommand: BaseMouseSpeed:750 BaseScrollSpeed:20 Layers:[0xc0000c02c0 0xc0000c0320 0xc0000c0520]} 
DEBU[0000] Switching to initial layer initial           
DEBU[0000] opening the keyboard device /dev/input/by-id/usb-CHESEN_USB_Keyboard-event-kbd 
DEBU[0000] Failed to open /dev/input/by-id/usb-CHESEN_USB_Keyboard-event-kbd: device or resource busy 
hhhhhDEBU[0005] opening the keyboard device /dev/input/by-id/usb-CHESEN_USB_Keyboard-event-kbd 
DEBU[0005] Failed to open /dev/input/by-id/usb-CHESEN_USB_Keyboard-event-kbd: device or resource busy 
                 DEBU[0010] opening the keyboard device /dev/input/by-id/usb-CHESEN_USB_Keyboard-event-kbd 
```

Mouseless works as it is supposed to if kmonad service is stopped using `systemctl stop kmonad.service`.

Here is my the mouseless config.yaml
```
devices:
  - "/dev/input/by-id/usb-CHESEN_USB_Keyboard-event-kbd"
baseMouseSpeed: 750.0
baseScrollSpeed: 20.0
layers:
  - name: initial
    bindings:
      tab: tap-hold tab ; toggle-layer mouse ; 300
  - name: mouse
    passThrough: true
    bindings:
      r: reload-config
      right: move  1  0
      left: move -1  0
      down: move  0  1
      up: move  0 -1
      f: button left
      d: button middle
      s: button right
```

I haven't remapped <kbd>tab</kbd> key in kmonad so it won't conflict.

Thanks for your patience and help.
