### ISSUE TITLE
The Wildcard `_` do not capture click

### ISSUE THREAD

**Issue by czhang03** [jbensmann/mouseless#48]
My use case is mainly using `caplock` as `control`, and use `control + h j k l` to send arrow keys. 
So I use `caplock` and `control` to toggle a cursor movement layer, which includes the mapping for `h j k l`, and use wildcard to capture the rest. 

However, now my `control + click` no longer works, since it is in the cursor movement layer. 

----

I think we can add a `passThroughAs` field, like `passThroughAs: ctrl`.
In the background, we will simply send the control key when the layer is activated. Until a key is pressed, then we will resolve whether that key mapped to another action in the current layer:
- if it is mapped to another key, release the control key and send the action.
- if it is not mapped to another key, send the key press.

**Comment by jbensmann** [comment]
Yeah the problem is that mouseless does not handle mouse events, so the wildcard does not apply to them.
But your suggestion sounds good, I will have a look at it.

Until then you could map an unused key in the cursor movement layer (or some other layer) to `ctrl`, but of course it is not the most comfortable having to press two keys for control.

**Comment by jbensmann** [comment]
For this use case there now is a new action `mod-layer` which changes specific keys if a modifier is pressed.
This could look like this:

```
layers:
- name: initial
  bindings:
    leftctrl: mod-layer leftctrl arrows
    capslock: mod-layer leftctrl arrows
- name: arrows
  bindings:
    h: left
    j: down
    k: up
    l: right
```

I found this to be a little better than defining a `passThroughAs` key in the layer `arrows` for various reasons, e.g. one could use different modifiers in different `mod-layer` bindings.
But otherwise it should behave the same.i
