### ISSUE TITLE
Fail to install mouseless

### ISSUE THREAD

**Issue by Bastien-mva** [jbensmann/mouseless#5]
Hello, 

Thanks for the repo. I was before using xmouseless, but with the upgrade of ubuntu to the 22.04 version, I had to rebuilt xmouseless but it did not worked anymore, so I am trying to make mouseless work. 

I am quite a novice, and I am trying to figure out how to make mouseless working. I have found my keyboard in ```"/dev/input/by-path/platform-i8042-serio-0-event-kbd ``` so that I replace this on the third line of the config.yaml file given in the configuration (only the third line has changed) : 

```
devices:
# change this to a keyboard device
- "/dev/input/by-path/platform-i8042-serio-0-event-kbd"
# this is executed when mouseless starts
# startCommand: ""
# the default speed for mouse movement
baseMouseSpeed: 750.0
# the default speed for scrolling
baseScrollSpeed: 20.0
layers:
# the first layer is active at start
- name: initial
  bindings:
    # when tab is held and another key pressed, activate mouse layer
    tab: tap-hold-next tab ; toggle-layer mouse ; 500
    # when a is held for 300ms, activate mouse layer
    a: tap-hold a ; toggle-layer mouse ; 300
    # right alt key toggles arrows layer
    rightalt: toggle-layer arrows
    # switch escape with capslock
    esc: capslock
    capslock: esc
# a layer for mouse movement
- name: mouse
  # when true, keys that are not mapped keep their original meaning
  passThrough: true
  bindings:
    # quit mouse layer
    q: layer initial
    # keep the mouse layer active
    space: layer mouse
    r: reload-config
    l: move  1  0
    j: move -1  0
    k: move  0  1
    i: move  0 -1
    p: scroll up
    n: scroll down
    leftalt: speed 4.0
    e: speed 0.3
    capslock: speed 0.1
    f: button left
    d: button middle
    s: button right
    # move to the top left corner
    k0: "exec xdotool mousemove 0 0"
# another layer for arrows and some other keys
- name: arrows
  passThrough: true
  bindings:
    e: up
    s: left
    d: down
    f: right
    q: esc
    w: backspace
    r: delete
    v: enter
```

  It is located in  ```~/.config/mouseless```. 

Since ```sudo mouseless --config ~/.config/mouseless/config.yaml ``` is returning ```mouseless: command not found```, I am guessing I have to install mouseless before, so that I ran ```./mouseless```  when I am on the ```dist``` directory downloaded previsouly, but it is giving me the following error: 

```ERRO[0000] Failed to init the virtual mouse: could not create relative axis input device: could not open device file  ```
Can anyone help me ? 

Thanks for your help.
