### ISSUE TITLE
possible to assign different hold time setting to the same key in same layer?

### ISSUE THREAD

**Issue by zerobikappa** [jbensmann/mouseless#52]
Few months ago, I found a method to use a single-key keyboard to control my virtual machine. I use `mouseless` to let the keyboard act like a shutdown button.
my single-key board (press the key will output "a"):
![Untitled](https://github.com/jbensmann/mouseless/assets/26425881/57992f7a-802e-4b37-b4aa-d6697aaff53c)

my service config file:
```
[Unit]
Description=mouseless

[Service]
ExecStart=/root/.local/bin/mouseless --config /root/.config/mouseless/config.pve-qemu.yaml

[Install]
WantedBy=multi-user.target
```

my `mouseless` config file:
```yaml
# the keyboard devices it reads from, if no devices are specified, it reads from all
devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"
 # keyboard to control VM102, assigned "a" key
 - "/dev/input/by-id/usb-SayoDevice_qm-pve-win-event-kbd"
 # keyboard to control VM103, assigned "b" key
 - "/dev/input/by-id/usb-SayoDevice_qm-pve-openwrt-event-kbd"

# the rest of the config defines the layers with their bindings
layers:
# the first layer is active at start
- name: initial
  bindings:
    #a: exec "/root/.local/bin/mouseless-vmctl start 102"
    a: tap-hold exec qm start 102 ; exec qm shutdown 102 ; 3000
    b: tap-hold exec qm start 103 ; exec qm restart 103 ; 3000
```

It works well that I can press the key to start my virtual machine and then hold the key for 3 seconds to shutdown my virtual machine.

However, recently I tried to assign more hold time setting to the same key but failed.
Is it possible to let the same key act like this?
press "a" key --> start virtual machine
hold "a" key for 3 second --> shutdown virtual machine
hold "a" key for 8 second --> force stop virtual machine
