### ISSUE TITLE
leftmeta+leftctrl combo not working?

### ISSUE THREAD

**Issue by AnthonySmithDev** [jbensmann/mouseless#58]
I want to map the `r` key so that when I hold it it executes the key combination `leftmeta+leftalt` but this doesn't seem to work. How can I make it so that when I hold down the `r` key and then the `1` key, it equals `leftmeta+leftalt+1`?

**Comment by AnthonySmithDev** [comment]
### Example

    r: tap-hold-next r ; leftmeta+leftctrl ; 150
    e: tap-hold-next e ; leftmeta+leftalt ; 150

    u: tap-hold-next u ; rightmeta+rightctrl ; 150
    i: tap-hold-next i ; rightmeta+rightalt ; 150

**Comment by jbensmann** [comment]
You're right, it does not work as expected, when holding `r` it presses `leftmeta` and `leftctrl`, but when pressing another key it releases the first modifier, `leftmeta` in this case.
I added this behavior to make it simpler to quickly press multiple key combos with different modifiers, but was not aware it would break something else. I will see how this can be fixed.

In the meantime, what could work for your use case is adding an additional layer for each combination of modifiers, e.g.
```
...
    r: tap-hold-next r ; toggle-layer leftmeta_leftctrl ; 150
    
- name: leftmeta_leftctrl
  bindings:
    _: leftmeta+leftctrl+_
```
