### ISSUE TITLE
how to make shortcut work with certain keys only

### ISSUE THREAD

**Issue by mashrit** [jbensmann/mouseless#60]
in the shortcuts i want when i press leftctrl+j it simulates down arrow
but when i press leftctrl+leftalt+j to not simulate leftalt+down arrow

i have tried
  ```
leftctrl: toggle-layer arrows

  name: arrows
  passThrough: false
  bindings:
    #for other shortcuts
    leftalt: layer initial
    leftmeta: layer initial
    leftshift: layer initial

    k: up
    h: left
    j: down
    l: right
    q: esc
    u: backspace
    i: delete
    o: enter
    # _ is the wildcard key, which matches any key that is not mapped
    _: leftctrl+_ 
```

this does not seem to work

PS: i have discovered this script only today so i minght not know all the intricacies
btw i love this script already

**Comment by mashrit** [comment]
solved using
```
name: arrows
  passThrough: false
  bindings:
    #for other shortcuts
    leftalt: toggle-layer leftctrl+leftalt
    leftmeta: toggle-layer leftctrl+leftmeta
    leftshift: toggle-layer leftctrl+leftshift

    k: up
    h: left
    j: down
    l: right
    q: esc
    u: backspace
    i: delete
    o: enter
    m: end
    n: home
    # _ is the wildcard key, which matches any key that is not mapped
    _: leftctrl+_

- name: leftctrl+leftalt
  passThrough: true
  bindings:
    _: leftctrl+leftalt+_



- name: leftctrl+leftshift
  passThrough: true
  bindings:
    _: leftctrl+leftshift+_

- name: leftctrl+leftmeta
  passThrough: true
  bindings:
    _: leftctrl+leftmeta+_
```
