### ISSUE TITLE
keyboard stops working

### ISSUE THREAD

**Issue by mashrit** [jbensmann/mouseless#61]
when i posted issue(more like question) #60 i tried to achive the result through other methods
then i tried
```
name: arrows
  passThrough: false
  bindings:
    #for other shortcuts
    leftalt: layer leftctrl+leftalt
    leftmeta: layer leftctrl+leftmeta
    leftshift: layer leftctrl+leftshift

    k: up
    h: left
    j: down
    l: right
    q: esc
    u: backspace
    i: delete
    o: enter
    m: end
    n: home
    # _ is the wildcard key, which matches any key that is not mapped
    _: leftctrl+_

- name: leftctrl+leftalt
  passThrough: false
  bindings:
  _: leftalt+leftctrl+_


- name: leftctrl+leftshift
  passThrough: false
  bindings:
  _: leftshift+leftctrl+_

- name: leftctrl+leftmeta
  passThrough: false
  bindings:
  _: leftmeta+leftctrl+_
```
using this, when i press leftalt+leftctrl+h the keyboard stops working 
it does not send any inputs(i checked using wev)
